### ISSUE TITLE
Responsive issues based on position

### ISSUE THREAD

**Issue by mjimenezleon13** [mjimenezleon13/clapHelp#37] opened 2020-04-05 03:34 UTC
There's responsive issues when the content of the page excedes the size of the screen in mobile view. In the third view "#help", there's overlap between the footer and header, and the content of the "#help".

**Comment by mjimenezleon13** [comment] 2020-04-05 03:40
Solved it by reducing the padding and the font size in que media query of a small screen.
However, leaving the issue open to discussion, as this seems like a problem likely to present itself again if the content of "#help# or any other body part changes.

**Comment by mjimenezleon13** [comment] 2020-04-05 03:42
Also set for discussion, it seems like the height of body when seen using the media query of screen is larger than 100vh (the page is scrolleable by some pixels). Is this mean to happen?

**Comment by aristizabal95** [comment] 2020-04-05 17:27
The overlap is caused by PR #36 due to the absolute and fixed positioning, and is still an issue.

About the 100vh, sadly yes, is an intentional effect taken by browsers to stop other bugs from happening. The scrolling is the same size as the url bar that hides once you scroll. https://stackoverflow.com/a/37113430/7275142

**Comment by aristizabal95** [comment] 2020-04-05 17:53
Now that we're not dealing with ordering, I guess we can close this now. If the issue presents, or there is more to discuss, feel free to open it again by writing a comment

**Closed by aristizabal95** 2020-04-05 17:53 UTC
